@startuml

' --- estilos ---
!include style/dark_minimal.puml

' --- diagrama ---
title CU1 - Configurar zonas de cultivo

|Administrador|
start

|Administrador|
:Seleccionar "Configurar Zonas";
|Sistema|
:Mostrar mapa/interfaz de zonificación;
|Administrador|
repeat
  fork
    :Definir polígono en el mapa;
  fork again
    :Asignar tipo de cultivo;
  fork again
    :Ingresar más datos;
  end fork
  |Sistema|
  fork
    
    :Validar datos ingresados;
  fork again

    :Generar previsualización de zona;
  end fork
|Sistema|
  if (¿Confirmar creación de zona?) then (Sí)
    :Guardar configuración en BD;
  else (No)
    :Eliminar borrador;
  
  endif
repeat while (¿Agregar más zonas?) is (Sí)
->No;
|Sistema|

:Confirmar creación de zonas;
end
@enduml