@startuml

' --- estilos ---
!include style/dark_minimal.puml

' --- diagrama ---
title CU2 - Programar riego


|Usuario/Admin|
start
repeat
:Seleccionar zona;



fork
  |Usuario/Admin|
  :Definir frecuencia (días/horas);
fork again
  |Sistema|

    :Mostrar datos de la zona seleccionada y meteorologicos;


fork again
  |Sistema|
  :Visualizar Consumo de agua;

|Usuario/Admin|

end fork
|Sistema|
:Calcular consumo de agua optimizado;

|Usuario/Admin|
if (¿Confirma programación?) then (No)

else (Sí)
  |Sistema|
  :Guardar programación;
  :Notificar éxito;
endif
|Usuario/Admin|
repeat while (¿Continuar programando riegos?) is (Sí)
->No;


end
@enduml
