@startuml CU4_EmitirAlertas

' --- estilos ---
'!include style/dark_minimal.puml

title "CU4 - Emitir alertas inteligentes"

|Usuario|
|Sistema|
start
:Monitorear variables cada 5 min;
fork
  if (¿Humedad < umbral?) then (Sí)
    :Generar alerta "Riesgo de sequía";
  else (No)
  endif
fork again
  if (¿Consumo agua > límite?) then (Sí)
    :Generar alerta "Sobreuso de agua";
  else (No)
  endif
end fork
|Usuario|
:Recibir notificación (email/app);
end
@enduml