@startuml

' --- estilos ---
'!include style/dark_minimal.puml

' --- diagrama ---
title CU6 - Ajustar riego automáticamente (Sistema)

|Sistema|
start
:Obtener datos del sensor;

fork
  :Analizar humedad y pH del suelo;
fork again
  :Consultar pronóstico climático;
end fork

if (¿Se requiere ajuste?) then (sí)
  :Modificar parámetros de riego;
'   object "Controlador de riego" as CR
  :Enviar nueva configuración;
'   CR --> :Confirmación de ajuste;
else (no)
  :Mantener configuración actual;
endif

end
@enduml
