@startuml

'si archivo no existe, coment out this line
!include style/dark_minimal.puml

left to right direction

actor "Admin" as Admin
actor "Usuario" as Usuario


rectangle "Sistema de Riego Inteligente" {
    usecase "CU10: Autenticarse y gestionar sesión" as CU10
    usecase "CU1: Configurar zonas de cultivo" as CU1
    usecase "CU2: Programar riego" as CU2

    usecase "CU3: Monitorear variables en vivo" as CU3
    usecase "CU5: Analizar datos históricos" as CU5

    usecase "CU7: Visualizar sugerencias" as CU7
    usecase "CU8: Control remoto del sistema" as CU8
   
    usecase "CU4: Emitir alertas inteligentes" as CU4
    usecase "CU6: Ajustar riego automáticamente" as CU6

    usecase "CU9: Generar informes de cumplimiento" as CU9
}

' Relaciones actores - casos

Usuario --> CU8
Usuario --> CU10

CU8 --> CU1
CU8 --> CU2
CU8 --> CU3
CU8 --> CU5
CU8 --> CU7
CU8 --> CU9


' Relaciones entre casos de uso

' includes
Admin ..> Usuario #green : <<include>> 
CU6 ..> CU2 #green : <<include>>

CU9 ..> CU5 #green : <<include>>
CU7 ..> CU5 #green : <<include>>
CU4 ..> CU5 #green : <<include>>

' extends
CU7 ..> CU3 #yellow : <<extend>>


@enduml
